ccxtbroker: don't use unparsed order properties
Used public order properties 'side' and 'amount' instead of
original unparsed properties ['info']['side'] and ['info']['original_amount'].
The latter are exchange-specific and may not be provided by
all exchanges.

This should fix crashes like this:
Traceback (most recent call last):
  File "machine_engin.py", line 161, in <module>
    cerebro.run()
  File "backtrader/cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "backtrader/cerebro.py", line 1295, in runstrategies
    self._runnext(runstrats)
  File "backtrader/cerebro.py", line 1626, in _runnext
    strat._next()
  File "backtrader/strategy.py", line 325, in _next
    super(Strategy, self)._next()
  File "backtrader/lineiterator.py", line 266, in _next
    self.next()
  File "machine_engin_prod.py", line 138, in next
    price=self.data0.close[0])
  File "backtrader/strategy.py", line 945, in sell
    **kwargs)
  File "backtrader/brokers/ccxtbroker.py", line 96, in sell
    return self._submit(owner, data, exectype, 'sell', size, price, kwargs)
  File "backtrader/brokers/ccxtbroker.py", line 82, in _submit
    order = CCXTOrder(owner, data, _order)
  File "backtrader/metabase.py", line 88, in __call__
    _obj, args, kwargs = cls.doinit(_obj, *args, **kwargs)
  File "backtrader/metabase.py", line 78, in doinit
    _obj.__init__(*args, **kwargs)
  File "backtrader/brokers/ccxtbroker.py", line 34, in __init__
    self.size = float(ccxt_order['info']['original_amount'])
KeyError: 'original_amount'

Signed-off-by: Ed Bartosh <bartosh@gmail.com>